<?php

namespace Lily\Console\Commands;

use Lily\Console\Command;

/**
 * Class ConfigGenerateCommand
 *
 * Command to generate server configuration files.
 *
 * @package Lily\Console\Commands
 */
class ConfigGenerateCommand extends Command
{
    /**
     * Get the name of the command.
     *
     * @return string The command name.
     */
    public function getName(): string
    {
        return 'config:generate';
    }

    /**
     * Execute the command to generate configuration files.
     *
     * @param array $args The arguments passed to the command.
     * @return int The exit status code.
     */
    public function execute(array $args): int
    {
        echo "Generating server configuration files...\n";
        
        $publicDir = dirname(__DIR__, 3) . '/public';
        if (!is_dir($publicDir)) {
            mkdir($publicDir, 0755, true);
        }

        $this->ensureHtaccess($publicDir);
        $this->ensureNginxSnippet($publicDir);
        $this->ensureWebConfig($publicDir);

        echo "Server configuration files generated in {$publicDir}\n";
        return 0;
    }

    /**
     * Ensure the .htaccess file exists in the public directory.
     *
     * @param string $publicDir The path to the public directory.
     * @return void
     */
    private function ensureHtaccess(string $publicDir): void
    {
        $path = $publicDir . '/.htaccess';
        if (file_exists($path)) return;

        $tpl = <<<HTACCESS
# Auto-generated by Lily
Options -Indexes -MultiViews
DirectoryIndex index.php

<FilesMatch "(^\.|\.)(ncache|log|env|bak|sql|sh|bash|ini|lock|phar|phtml)$">
    Require all denied
</FilesMatch>

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^ index.php [QSA,L]
</IfModule>
HTACCESS;
        file_put_contents($path, $tpl);
        echo "Created .htaccess\n";
    }

    /**
     * Ensure the nginx configuration snippet exists in the public directory.
     *
     * @param string $publicDir The path to the public directory.
     * @return void
     */
    private function ensureNginxSnippet(string $publicDir): void
    {
        $path = $publicDir . '/nginx.conf.example';
        if (file_exists($path)) return;

        $tpl = <<<NGINX
# Auto-generated by Lily
# Include this within your server { ... } block

index index.php;

location / {
    try_files \$uri \$uri/ /index.php?\$query_string;
}

location ~ \.(ncache|log|env|bak|sql|sh|bash|ini|lock|phar|phtml)$ {
    deny all;
}
NGINX;
        file_put_contents($path, $tpl);
        echo "Created nginx.conf.example\n";
    }

    /**
     * Ensure the web.config file exists in the public directory.
     *
     * @param string $publicDir The path to the public directory.
     * @return void
     */
    private function ensureWebConfig(string $publicDir): void
    {
        $path = $publicDir . '/web.config';
        if (file_exists($path)) return;

        $tpl = <<<WEBCONFIG
<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-generated by Lily -->
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="Lily Framework" stopProcessing="true">
                    <match url="^" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll">
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="index.php" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
WEBCONFIG;
        file_put_contents($path, $tpl);
        echo "Created web.config\n";
    }
}
